[run]
build = "npm run build"
test = "npm run test"
lint = "npm run lint"

[paths]
dist = "./build"
src = "./src"

[gptengineer-app]  # this namespace is used for gptengineer.app, we can use this for internal experiments
project_id = "8677d20e-6663-4538-9341-6854827b6d20"
